### ISSUE TITLE
Tables are inconsistent throughout application

### ISSUE THREAD

**Issue by pkitazos** [pkitazos/allocation-app#95]
**Current state**
- certain tables in the admin panel contain very limited information and functionality
- destructive actions are not always displayed the same way
- selection columns are not consistently hidden

**TODO**
- [ ] replace simple tables with DataTables
- [ ] add tooltips to all partially hidden labels and icon-only buttons
- [ ] ensure all action menus are styled the same way
- [ ] decouple all tables data model from database data model
- [ ] refactor column constructors to accept object of dependencies
- [ ] refactor column constructors to get instance stage from context
